#!/usr/bin/env bun
// Generate `src/version.ts` from package.json so the `VERSION` export is a plain
// static constant — no runtime filesystem read and no Bun-API coupling at import
// time (the old `await Bun.file(...).json()` in src/index.ts crashed the import
// on any non-Bun runtime, which broke the runner-agnostic assertion layer).
//
// package.json stays the single source of truth: this runs in `prepare` (before
// the type build) so the published tarball always carries a fresh value, and the
// generated file is committed so fresh clones / npm tarballs work with no codegen
// step. Run manually with `bun run gen:version`.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const root = new URL('../', import.meta.url)
const { version } = JSON.parse(readFileSync(new URL('package.json', root), 'utf8'))
const out = fileURLToPath(new URL('src/version.ts', root))

const banner =
  '// Generated by scripts/gen-version.mjs from package.json — do not edit by hand.\n'
writeFileSync(out, `${banner}export const VERSION: string = ${JSON.stringify(version)}\n`)
console.log(`gen-version: wrote VERSION = ${version}`)
